version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY: 1
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  data-mysql:
    driver: local