on: 
  push:
    branches:
      - 'main'

jobs: 
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate tag
        id: tag
        run: echo "::set-output name=tag::nguyeson/fruit_sale_v1:${{ github.sha }}"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend 
          push: true
          tags: ${{ steps.tag.outputs.tag }}
